export type AgeGroup = 'child' | 'adult' | 'senior' | 'pregnant';
export type Category = 'trauma' | 'unconscious';
export type EmergencyType = 'bleeding' | 'fracture' | 'burn' | 'heartAttack' | 'fits' | 'poisoning' | 'choking' | 'childbirth';
export type Language = 'en' | 'hi' | 'es' | 'fr' | 'zh';

export const LANGUAGES: { code: Language; label: string; native: string }[] = [
  { code: 'en', label: 'English', native: 'English' },
  { code: 'hi', label: 'Hindi', native: 'हिंदी' },
  { code: 'es', label: 'Spanish', native: 'Español' },
  { code: 'fr', label: 'French', native: 'Français' },
  { code: 'zh', label: 'Chinese', native: '中文' },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    helpNow: 'HELP NOW',
    traumaCare: 'Trauma Care',
    unconscious: 'Unconscious',
    selectAge: 'Select Patient Age Group',
    child: 'Child (0-12)',
    adult: 'Adult (13-60)',
    senior: 'Senior (60+)',
    pregnant: 'Pregnant',
    selectEmergency: 'Select Emergency Type',
    bleeding: 'Bleeding',
    fracture: 'Fracture',
    burn: 'Burn',
    heartAttack: 'Heart Attack',
    fits: 'Fits/Seizure',
    poisoning: 'Poisoning',
    choking: 'Choking',
    childbirth: 'Childbirth',
    firstAidTips: 'First Aid Tips',
    yes: 'YES',
    no: 'NO',
    next: 'Next',
    findHospital: 'Find Nearest Hospital',
    patientAdmitted: 'Patient Admitted',
    wellDone: 'Well Done!',
    thankYou: 'Thank you for saving a life',
    breathe: 'Take a deep breath now. You did great.',
    summary: 'Patient Summary',
    emergencyType: 'Emergency Type',
    timeTaken: 'Time Taken',
    ageGroup: 'Age Group',
    category: 'Category',
    language: 'Language',
    back: 'Back',
    nearestHospital: 'Nearest Hospital',
    navigateToHospital: 'Navigate to Hospital',
    stopReading: 'Stop Reading',
    readAloud: 'Read Aloud',
    elapsed: 'Elapsed',
    triageQuestions: 'Quick Assessment',
  },
  hi: {
    helpNow: 'अभी मदद',
    traumaCare: 'आघात देखभाल',
    unconscious: 'बेहोश',
    selectAge: 'रोगी की आयु वर्ग चुनें',
    child: 'बच्चा (0-12)',
    adult: 'वयस्क (13-60)',
    senior: 'वरिष्ठ (60+)',
    pregnant: 'गर्भवती',
    selectEmergency: 'आपातकालीन प्रकार चुनें',
    bleeding: 'रक्तस्राव',
    fracture: 'फ्रैक्चर',
    burn: 'जलना',
    heartAttack: 'दिल का दौरा',
    fits: 'दौरे',
    poisoning: 'विषाक्तता',
    choking: 'दम घुटना',
    childbirth: 'प्रसव',
    firstAidTips: 'प्राथमिक चिकित्सा',
    yes: 'हाँ',
    no: 'नहीं',
    next: 'अगला',
    findHospital: 'निकटतम अस्पताल खोजें',
    patientAdmitted: 'मरीज भर्ती',
    wellDone: 'शाबाश!',
    thankYou: 'जीवन बचाने के लिए धन्यवाद',
    breathe: 'अब गहरी सांस लें। आपने बहुत अच्छा किया।',
    summary: 'रोगी सारांश',
    emergencyType: 'आपातकालीन प्रकार',
    timeTaken: 'समय लगा',
    ageGroup: 'आयु वर्ग',
    category: 'श्रेणी',
    language: 'भाषा',
    back: 'वापस',
    nearestHospital: 'निकटतम अस्पताल',
    navigateToHospital: 'अस्पताल जाएं',
    stopReading: 'पढ़ना बंद करें',
    readAloud: 'जोर से पढ़ें',
    elapsed: 'बीता समय',
    triageQuestions: 'त्वरित मूल्यांकन',
  },
  es: {
    helpNow: 'AYUDA AHORA',
    traumaCare: 'Atención Trauma',
    unconscious: 'Inconsciente',
    selectAge: 'Seleccionar Grupo de Edad',
    child: 'Niño (0-12)',
    adult: 'Adulto (13-60)',
    senior: 'Mayor (60+)',
    pregnant: 'Embarazada',
    selectEmergency: 'Seleccionar Emergencia',
    bleeding: 'Sangrado',
    fracture: 'Fractura',
    burn: 'Quemadura',
    heartAttack: 'Infarto',
    fits: 'Convulsiones',
    poisoning: 'Envenenamiento',
    choking: 'Asfixia',
    childbirth: 'Parto',
    firstAidTips: 'Primeros Auxilios',
    yes: 'SÍ',
    no: 'NO',
    next: 'Siguiente',
    findHospital: 'Buscar Hospital',
    patientAdmitted: 'Paciente Admitido',
    wellDone: '¡Bien Hecho!',
    thankYou: 'Gracias por salvar una vida',
    breathe: 'Respira profundo. Lo hiciste genial.',
    summary: 'Resumen del Paciente',
    emergencyType: 'Tipo de Emergencia',
    timeTaken: 'Tiempo',
    ageGroup: 'Grupo de Edad',
    category: 'Categoría',
    language: 'Idioma',
    back: 'Atrás',
    nearestHospital: 'Hospital Cercano',
    navigateToHospital: 'Navegar al Hospital',
    stopReading: 'Dejar de Leer',
    readAloud: 'Leer en Voz Alta',
    elapsed: 'Transcurrido',
    triageQuestions: 'Evaluación Rápida',
  },
  fr: {
    helpNow: 'AIDE MAINTENANT',
    traumaCare: 'Soins Trauma',
    unconscious: 'Inconscient',
    selectAge: "Sélectionner le Groupe d'Âge",
    child: 'Enfant (0-12)',
    adult: 'Adulte (13-60)',
    senior: 'Senior (60+)',
    pregnant: 'Enceinte',
    selectEmergency: "Type d'Urgence",
    bleeding: 'Saignement',
    fracture: 'Fracture',
    burn: 'Brûlure',
    heartAttack: 'Crise Cardiaque',
    fits: 'Convulsions',
    poisoning: 'Empoisonnement',
    choking: 'Étouffement',
    childbirth: 'Accouchement',
    firstAidTips: 'Premiers Secours',
    yes: 'OUI',
    no: 'NON',
    next: 'Suivant',
    findHospital: 'Trouver Hôpital',
    patientAdmitted: 'Patient Admis',
    wellDone: 'Bien Joué!',
    thankYou: 'Merci d\'avoir sauvé une vie',
    breathe: 'Respirez profondément. Vous avez fait du bon travail.',
    summary: 'Résumé du Patient',
    emergencyType: "Type d'Urgence",
    timeTaken: 'Temps',
    ageGroup: "Groupe d'Âge",
    category: 'Catégorie',
    language: 'Langue',
    back: 'Retour',
    nearestHospital: 'Hôpital le Plus Proche',
    navigateToHospital: "Naviguer vers l'Hôpital",
    stopReading: 'Arrêter la Lecture',
    readAloud: 'Lire à Haute Voix',
    elapsed: 'Écoulé',
    triageQuestions: 'Évaluation Rapide',
  },
  zh: {
    helpNow: '立即求助',
    traumaCare: '创伤护理',
    unconscious: '失去意识',
    selectAge: '选择患者年龄组',
    child: '儿童 (0-12)',
    adult: '成人 (13-60)',
    senior: '老年人 (60+)',
    pregnant: '孕妇',
    selectEmergency: '选择紧急类型',
    bleeding: '出血',
    fracture: '骨折',
    burn: '烧伤',
    heartAttack: '心脏病发作',
    fits: '癫痫发作',
    poisoning: '中毒',
    choking: '窒息',
    childbirth: '分娩',
    firstAidTips: '急救提示',
    yes: '是',
    no: '否',
    next: '下一步',
    findHospital: '查找最近医院',
    patientAdmitted: '患者已入院',
    wellDone: '做得好！',
    thankYou: '感谢您拯救生命',
    breathe: '现在深呼吸。你做得很好。',
    summary: '患者摘要',
    emergencyType: '紧急类型',
    timeTaken: '耗时',
    ageGroup: '年龄组',
    category: '类别',
    language: '语言',
    back: '返回',
    nearestHospital: '最近的医院',
    navigateToHospital: '导航到医院',
    stopReading: '停止朗读',
    readAloud: '朗读',
    elapsed: '已用时间',
    triageQuestions: '快速评估',
  },
};

export const EMERGENCY_ICONS: Record<EmergencyType, { name: string; family: string }> = {
  bleeding: { name: 'water', family: 'Ionicons' },
  fracture: { name: 'body', family: 'Ionicons' },
  burn: { name: 'flame', family: 'Ionicons' },
  heartAttack: { name: 'heart', family: 'Ionicons' },
  fits: { name: 'flash', family: 'Ionicons' },
  poisoning: { name: 'skull', family: 'Ionicons' },
  choking: { name: 'hand-left', family: 'Ionicons' },
  childbirth: { name: 'people', family: 'Ionicons' },
};

export const EMERGENCY_COLORS: Record<EmergencyType, string> = {
  bleeding: '#E53935',
  fracture: '#FB8C00',
  burn: '#FF5722',
  heartAttack: '#D32F2F',
  fits: '#7B1FA2',
  poisoning: '#388E3C',
  choking: '#1565C0',
  childbirth: '#E91E63',
};

export function getEmergencyTypes(ageGroup: AgeGroup): EmergencyType[] {
  const base: EmergencyType[] = ['bleeding', 'fracture', 'burn', 'heartAttack', 'fits', 'poisoning', 'choking'];
  if (ageGroup === 'pregnant') {
    return [...base, 'childbirth'];
  }
  return base;
}

export interface TriageQuestion {
  question: Record<Language, string>;
}

export const TRIAGE_QUESTIONS: Record<EmergencyType, TriageQuestion[]> = {
  bleeding: [
    { question: { en: 'Is the bleeding severe or spurting?', hi: 'क्या रक्तस्राव गंभीर है?', es: '¿El sangrado es severo?', fr: 'Le saignement est-il sévère?', zh: '出血严重吗？' } },
    { question: { en: 'Is the patient conscious?', hi: 'क्या मरीज होश में है?', es: '¿El paciente está consciente?', fr: 'Le patient est-il conscient?', zh: '患者有意识吗？' } },
    { question: { en: 'Can you see the wound clearly?', hi: 'क्या आप घाव देख सकते हैं?', es: '¿Puede ver la herida?', fr: 'Pouvez-vous voir la blessure?', zh: '您能看到伤口吗？' } },
  ],
  fracture: [
    { question: { en: 'Is the bone visibly deformed?', hi: 'क्या हड्डी विकृत दिख रही है?', es: '¿El hueso está visiblemente deformado?', fr: "L'os est-il visiblement déformé?", zh: '骨头明显变形吗？' } },
    { question: { en: 'Can the patient move the injured area?', hi: 'क्या मरीज चोट वाला हिस्सा हिला सकता है?', es: '¿Puede mover el área lesionada?', fr: 'Le patient peut-il bouger la zone?', zh: '患者能移动受伤部位吗？' } },
    { question: { en: 'Is there swelling at the injury site?', hi: 'क्या चोट वाली जगह पर सूजन है?', es: '¿Hay hinchazón en el sitio?', fr: 'Y a-t-il un gonflement?', zh: '受伤部位有肿胀吗？' } },
  ],
  burn: [
    { question: { en: 'Is the burn larger than your palm?', hi: 'क्या जलन आपकी हथेली से बड़ी है?', es: '¿La quemadura es mayor que su palma?', fr: 'La brûlure est-elle plus grande que votre paume?', zh: '烧伤面积比手掌大吗？' } },
    { question: { en: 'Are there blisters forming?', hi: 'क्या फफोले बन रहे हैं?', es: '¿Se están formando ampollas?', fr: 'Des cloques se forment-elles?', zh: '有水泡吗？' } },
    { question: { en: 'Is the skin charred or white?', hi: 'क्या त्वचा जली हुई या सफेद है?', es: '¿La piel está carbonizada o blanca?', fr: 'La peau est-elle carbonisée ou blanche?', zh: '皮肤焦黑或发白吗？' } },
  ],
  heartAttack: [
    { question: { en: 'Is the patient experiencing chest pain?', hi: 'क्या मरीज को सीने में दर्द है?', es: '¿El paciente tiene dolor en el pecho?', fr: 'Le patient a-t-il une douleur thoracique?', zh: '患者胸痛吗？' } },
    { question: { en: 'Is the patient breathing normally?', hi: 'क्या मरीज सामान्य रूप से सांस ले रहा है?', es: '¿El paciente respira normalmente?', fr: 'Le patient respire-t-il normalement?', zh: '患者呼吸正常吗？' } },
    { question: { en: 'Has the patient taken aspirin?', hi: 'क्या मरीज ने एस्पिरिन ली है?', es: '¿El paciente ha tomado aspirina?', fr: 'Le patient a-t-il pris de l\'aspirine?', zh: '患者服过阿司匹林吗？' } },
  ],
  fits: [
    { question: { en: 'Has the seizure lasted more than 5 minutes?', hi: 'क्या दौरा 5 मिनट से अधिक चला?', es: '¿La convulsión duró más de 5 minutos?', fr: 'La crise dure-t-elle depuis plus de 5 minutes?', zh: '发作超过5分钟了吗？' } },
    { question: { en: 'Is this the first seizure?', hi: 'क्या यह पहला दौरा है?', es: '¿Es la primera convulsión?', fr: 'Est-ce la première crise?', zh: '这是第一次发作吗？' } },
    { question: { en: 'Is the patient injured from the seizure?', hi: 'क्या दौरे से मरीज को चोट लगी?', es: '¿El paciente se lesionó?', fr: 'Le patient est-il blessé?', zh: '患者因发作受伤了吗？' } },
  ],
  poisoning: [
    { question: { en: 'Do you know what substance was ingested?', hi: 'क्या आप जानते हैं कौन सा पदार्थ खाया गया?', es: '¿Sabe qué sustancia se ingirió?', fr: 'Savez-vous quelle substance a été ingérée?', zh: '您知道摄入了什么物质吗？' } },
    { question: { en: 'Is the patient vomiting?', hi: 'क्या मरीज को उल्टी हो रही है?', es: '¿El paciente está vomitando?', fr: 'Le patient vomit-il?', zh: '患者在呕吐吗？' } },
    { question: { en: 'Was it ingested within the last hour?', hi: 'क्या एक घंटे के अंदर खाया गया?', es: '¿Se ingirió en la última hora?', fr: "A-t-il été ingéré dans la dernière heure?", zh: '是在一小时内摄入的吗？' } },
  ],
  choking: [
    { question: { en: 'Can the patient cough or speak?', hi: 'क्या मरीज खांस या बोल सकता है?', es: '¿Puede el paciente toser o hablar?', fr: 'Le patient peut-il tousser ou parler?', zh: '患者能咳嗽或说话吗？' } },
    { question: { en: 'Is the patient turning blue?', hi: 'क्या मरीज नीला पड़ रहा है?', es: '¿El paciente se está poniendo azul?', fr: 'Le patient devient-il bleu?', zh: '患者变蓝了吗？' } },
    { question: { en: 'Is the patient still conscious?', hi: 'क्या मरीज अभी भी होश में है?', es: '¿El paciente sigue consciente?', fr: 'Le patient est-il encore conscient?', zh: '患者还有意识吗？' } },
  ],
  childbirth: [
    { question: { en: 'Are contractions less than 2 minutes apart?', hi: 'क्या संकुचन 2 मिनट से कम अंतर पर हैं?', es: '¿Las contracciones están a menos de 2 minutos?', fr: 'Les contractions sont-elles à moins de 2 minutes?', zh: '宫缩间隔不到2分钟吗？' } },
    { question: { en: 'Has the water broken?', hi: 'क्या पानी की थैली फट गई?', es: '¿Se rompió la fuente?', fr: 'La poche des eaux est-elle rompue?', zh: '破水了吗？' } },
    { question: { en: 'Can you see the baby\'s head?', hi: 'क्या आप बच्चे का सिर देख सकते हैं?', es: '¿Puede ver la cabeza del bebé?', fr: 'Pouvez-vous voir la tête du bébé?', zh: '能看到婴儿的头吗？' } },
  ],
};

export interface FirstAidTip {
  steps: Record<Language, string[]>;
}

export const FIRST_AID_TIPS: Record<EmergencyType, Record<AgeGroup, FirstAidTip>> = {
  bleeding: {
    child: { steps: {
      en: ['Apply firm pressure with a clean cloth', 'Keep the child calm and still', 'Elevate the wound above the heart', 'Do not remove the cloth if soaked, add more layers'],
      hi: ['साफ कपड़े से दबाव डालें', 'बच्चे को शांत रखें', 'घाव को ऊपर उठाएं', 'भीगा कपड़ा न हटाएं, और परतें जोड़ें'],
      es: ['Aplique presión firme con un paño limpio', 'Mantenga al niño calmado', 'Eleve la herida sobre el corazón', 'No retire el paño, agregue más capas'],
      fr: ['Appliquez une pression ferme avec un tissu propre', 'Gardez l\'enfant calme', 'Élevez la blessure au-dessus du coeur', 'N\'enlevez pas le tissu, ajoutez des couches'],
      zh: ['用干净布料用力按压', '让孩子保持冷静', '将伤口抬高到心脏以上', '不要移除布料，添加更多层'],
    }},
    adult: { steps: {
      en: ['Apply direct pressure with a clean cloth', 'If possible, use gloves for protection', 'Elevate the injured limb', 'Apply a pressure bandage if available'],
      hi: ['साफ कपड़े से सीधा दबाव डालें', 'दस्ताने पहनें', 'घायल अंग को ऊपर उठाएं', 'प्रेशर बैंडेज लगाएं'],
      es: ['Aplique presión directa con un paño limpio', 'Use guantes si es posible', 'Eleve el miembro lesionado', 'Aplique un vendaje de presión'],
      fr: ['Appliquez une pression directe avec un tissu propre', 'Utilisez des gants si possible', 'Élevez le membre blessé', 'Appliquez un bandage de pression'],
      zh: ['用干净布料直接按压', '尽可能戴手套保护', '抬高受伤的肢体', '如有可用绷带加压包扎'],
    }},
    senior: { steps: {
      en: ['Apply gentle but firm pressure', 'Check if patient takes blood thinners', 'Monitor for signs of shock', 'Keep the patient warm and comfortable'],
      hi: ['हल्का लेकिन मजबूत दबाव डालें', 'रक्त पतला करने वाली दवा की जांच करें', 'सदमे के संकेतों पर नजर रखें', 'मरीज को गर्म रखें'],
      es: ['Aplique presión suave pero firme', 'Verifique si toma anticoagulantes', 'Controle signos de shock', 'Mantenga al paciente abrigado'],
      fr: ['Appliquez une pression douce mais ferme', 'Vérifiez les anticoagulants', 'Surveillez les signes de choc', 'Gardez le patient au chaud'],
      zh: ['施加柔和但稳定的压力', '检查患者是否服用血液稀释药物', '监测休克迹象', '保持患者温暖舒适'],
    }},
    pregnant: { steps: {
      en: ['Apply pressure to stop bleeding', 'Position patient on left side', 'Monitor for contractions', 'Keep patient calm, call emergency services'],
      hi: ['रक्तस्राव रोकने के लिए दबाव डालें', 'मरीज को बाईं ओर लिटाएं', 'संकुचन पर नजर रखें', 'मरीज को शांत रखें'],
      es: ['Aplique presión para detener el sangrado', 'Posicione a la paciente del lado izquierdo', 'Controle las contracciones', 'Mantenga la calma, llame a emergencias'],
      fr: ['Appliquez une pression pour arrêter le saignement', 'Positionnez la patiente sur le côté gauche', 'Surveillez les contractions', 'Gardez la patiente calme'],
      zh: ['按压止血', '让患者左侧卧位', '监测宫缩', '保持患者冷静，呼叫急救服务'],
    }},
  },
  fracture: {
    child: { steps: {
      en: ['Do not move the injured area', 'Immobilize with a splint or padding', 'Apply ice wrapped in cloth', 'Comfort the child and keep still'],
      hi: ['घायल क्षेत्र को न हिलाएं', 'स्प्लिंट से स्थिर करें', 'कपड़े में लिपटी बर्फ लगाएं', 'बच्चे को आराम दें'],
      es: ['No mueva el área lesionada', 'Inmovilice con una férula', 'Aplique hielo envuelto en tela', 'Consuele al niño'],
      fr: ['Ne bougez pas la zone blessée', 'Immobilisez avec une attelle', 'Appliquez de la glace dans un tissu', 'Réconfortez l\'enfant'],
      zh: ['不要移动受伤部位', '用夹板固定', '用布包裹冰块敷', '安慰孩子保持不动'],
    }},
    adult: { steps: {
      en: ['Immobilize the fracture area', 'Do not try to realign the bone', 'Apply ice to reduce swelling', 'Support the limb in a comfortable position'],
      hi: ['फ्रैक्चर क्षेत्र को स्थिर करें', 'हड्डी को सीधा न करें', 'सूजन कम करने के लिए बर्फ लगाएं', 'अंग को आरामदायक स्थिति में सहारा दें'],
      es: ['Inmovilice el área de fractura', 'No intente realinear el hueso', 'Aplique hielo para reducir hinchazón', 'Soporte el miembro en posición cómoda'],
      fr: ['Immobilisez la zone de fracture', 'N\'essayez pas de réaligner l\'os', 'Appliquez de la glace', 'Soutenez le membre confortablement'],
      zh: ['固定骨折部位', '不要试图复位骨头', '冰敷减少肿胀', '将肢体放在舒适的位置支撑'],
    }},
    senior: { steps: {
      en: ['Handle very gently - bones are fragile', 'Immobilize without moving patient', 'Watch for signs of shock', 'Keep patient warm and still'],
      hi: ['बहुत धीरे से संभालें', 'बिना हिलाए स्थिर करें', 'सदमे के संकेतों पर नजर रखें', 'मरीज को गर्म और स्थिर रखें'],
      es: ['Maneje con mucho cuidado', 'Inmovilice sin mover al paciente', 'Observe signos de shock', 'Mantenga al paciente abrigado'],
      fr: ['Manipulez très doucement', 'Immobilisez sans bouger le patient', 'Surveillez les signes de choc', 'Gardez le patient au chaud'],
      zh: ['非常轻柔地处理-骨骼脆弱', '不移动患者进行固定', '注意休克迹象', '保持患者温暖静止'],
    }},
    pregnant: { steps: {
      en: ['Immobilize the fracture gently', 'Position on left side if possible', 'Monitor both mother and baby', 'Do not give any medication without medical advice'],
      hi: ['फ्रैक्चर को धीरे से स्थिर करें', 'बाईं ओर लिटाएं', 'माँ और बच्चे दोनों पर नजर रखें', 'बिना डॉक्टर की सलाह दवा न दें'],
      es: ['Inmovilice la fractura suavemente', 'Posicione del lado izquierdo', 'Controle a madre y bebé', 'No dé medicamentos sin consejo médico'],
      fr: ['Immobilisez doucement la fracture', 'Positionnez sur le côté gauche', 'Surveillez mère et bébé', 'Pas de médicaments sans avis médical'],
      zh: ['轻柔固定骨折', '尽可能让患者左侧卧', '同时监护母亲和婴儿', '未经医嘱不要给药'],
    }},
  },
  burn: {
    child: { steps: {
      en: ['Cool the burn under running water for 10 min', 'Remove clothing near burn carefully', 'Cover with cling film or clean cloth', 'Do not apply creams or butter'],
      hi: ['10 मिनट तक बहते पानी में ठंडा करें', 'जले के पास कपड़े सावधानी से हटाएं', 'क्लिंग फिल्म या साफ कपड़े से ढकें', 'क्रीम या मक्खन न लगाएं'],
      es: ['Enfríe bajo agua corriente por 10 min', 'Retire la ropa cerca de la quemadura', 'Cubra con film o paño limpio', 'No aplique cremas ni mantequilla'],
      fr: ['Refroidissez sous l\'eau courante 10 min', 'Retirez les vêtements prudemment', 'Couvrez avec un film ou tissu propre', 'N\'appliquez pas de crème ou beurre'],
      zh: ['在流水下冷却烧伤处10分钟', '小心移除烧伤附近的衣物', '用保鲜膜或干净布覆盖', '不要涂抹药膏或黄油'],
    }},
    adult: { steps: {
      en: ['Cool under running water for 10-20 min', 'Remove jewelry and tight clothing', 'Cover loosely with sterile bandage', 'Take over-the-counter pain relief if needed'],
      hi: ['10-20 मिनट बहते पानी में ठंडा करें', 'गहने और तंग कपड़े हटाएं', 'स्टरिल बैंडेज से ढीला ढकें', 'दर्द निवारक लें'],
      es: ['Enfríe bajo agua corriente 10-20 min', 'Retire joyas y ropa ajustada', 'Cubra con vendaje estéril', 'Tome analgésicos si es necesario'],
      fr: ['Refroidissez sous l\'eau 10-20 min', 'Retirez bijoux et vêtements serrés', 'Couvrez avec un bandage stérile', 'Prenez un antidouleur si nécessaire'],
      zh: ['在流水下冷却10-20分钟', '移除首饰和紧身衣物', '用无菌绷带松散覆盖', '必要时服用止痛药'],
    }},
    senior: { steps: {
      en: ['Cool gently under lukewarm water', 'Be careful of fragile skin', 'Cover with non-stick dressing', 'Monitor for infection signs'],
      hi: ['गुनगुने पानी से धीरे ठंडा करें', 'नाजुक त्वचा का ध्यान रखें', 'नॉन-स्टिक ड्रेसिंग से ढकें', 'संक्रमण के संकेतों पर नजर रखें'],
      es: ['Enfríe suavemente con agua tibia', 'Cuide la piel frágil', 'Cubra con apósito antiadherente', 'Controle signos de infección'],
      fr: ['Refroidissez doucement à l\'eau tiède', 'Attention à la peau fragile', 'Couvrez avec un pansement non-adhérent', 'Surveillez les signes d\'infection'],
      zh: ['用温水轻柔冷却', '注意脆弱的皮肤', '用不粘敷料覆盖', '监测感染迹象'],
    }},
    pregnant: { steps: {
      en: ['Cool the burn under running water', 'Do not apply any medicated cream', 'Cover with clean, non-stick dressing', 'Seek medical help immediately'],
      hi: ['बहते पानी में जलन ठंडा करें', 'कोई दवा वाली क्रीम न लगाएं', 'साफ नॉन-स्टिक ड्रेसिंग से ढकें', 'तुरंत चिकित्सा सहायता लें'],
      es: ['Enfríe bajo agua corriente', 'No aplique crema medicada', 'Cubra con apósito limpio', 'Busque ayuda médica inmediata'],
      fr: ['Refroidissez sous l\'eau courante', 'N\'appliquez pas de crème médicamentée', 'Couvrez avec un pansement propre', 'Consultez immédiatement'],
      zh: ['在流水下冷却烧伤', '不要涂抹药膏', '用干净不粘敷料覆盖', '立即寻求医疗帮助'],
    }},
  },
  heartAttack: {
    child: { steps: {
      en: ['Call emergency services immediately', 'Keep the child calm and resting', 'Loosen any tight clothing', 'Monitor breathing closely'],
      hi: ['तुरंत आपातकालीन सेवाओं को कॉल करें', 'बच्चे को शांत रखें', 'तंग कपड़े ढीले करें', 'श्वास पर नजर रखें'],
      es: ['Llame a emergencias inmediatamente', 'Mantenga al niño calmado', 'Afloje la ropa ajustada', 'Controle la respiración'],
      fr: ['Appelez les urgences immédiatement', 'Gardez l\'enfant calme', 'Desserrez les vêtements', 'Surveillez la respiration'],
      zh: ['立即拨打急救电话', '让孩子保持冷静休息', '松开紧身衣物', '密切监测呼吸'],
    }},
    adult: { steps: {
      en: ['Call emergency services immediately', 'Give aspirin if not allergic (chew it)', 'Help patient sit in W position', 'Be ready to perform CPR if needed'],
      hi: ['तुरंत आपातकालीन सेवा कॉल करें', 'एलर्जी नहीं तो एस्पिरिन दें', 'W स्थिति में बिठाएं', 'CPR के लिए तैयार रहें'],
      es: ['Llame a emergencias inmediatamente', 'Dé aspirina si no es alérgico', 'Ayude a sentarse en posición W', 'Esté listo para RCP'],
      fr: ['Appelez les urgences', 'Donnez de l\'aspirine si pas allergique', 'Aidez en position W', 'Soyez prêt pour la RCP'],
      zh: ['立即拨打急救电话', '如不过敏给阿司匹林（咀嚼）', '帮助患者坐成W形', '准备好进行心肺复苏'],
    }},
    senior: { steps: {
      en: ['Call emergency immediately', 'Check for medication (nitroglycerin)', 'Help into comfortable sitting position', 'Monitor breathing, prepare for CPR'],
      hi: ['तुरंत आपातकालीन कॉल करें', 'दवा की जांच करें', 'आरामदायक स्थिति में बिठाएं', 'श्वास की निगरानी करें'],
      es: ['Llame a emergencias inmediatamente', 'Verifique medicamentos', 'Ayude a sentarse cómodamente', 'Controle respiración, prepare RCP'],
      fr: ['Appelez les urgences', 'Vérifiez les médicaments', 'Position assise confortable', 'Surveillez la respiration'],
      zh: ['立即拨打急救', '检查药物（硝化甘油）', '帮助坐到舒适位置', '监测呼吸，准备心肺复苏'],
    }},
    pregnant: { steps: {
      en: ['Call emergency immediately', 'Position on left side', 'Loosen all tight clothing', 'Do not give aspirin - monitor breathing'],
      hi: ['तुरंत आपातकालीन कॉल करें', 'बाईं ओर लिटाएं', 'सभी तंग कपड़े ढीले करें', 'एस्पिरिन न दें'],
      es: ['Llame a emergencias inmediatamente', 'Posicione del lado izquierdo', 'Afloje toda la ropa', 'No dé aspirina'],
      fr: ['Appelez les urgences', 'Position sur le côté gauche', 'Desserrez tous les vêtements', 'Ne donnez pas d\'aspirine'],
      zh: ['立即拨打急救', '让患者左侧卧位', '松开所有紧身衣物', '不要给阿司匹林-监测呼吸'],
    }},
  },
  fits: {
    child: { steps: {
      en: ['Clear area of dangerous objects', 'Do NOT hold the child down', 'Place on side after seizure stops', 'Time the seizure duration'],
      hi: ['खतरनाक वस्तुएं हटाएं', 'बच्चे को पकड़ें नहीं', 'दौरा रुकने पर करवट पर लिटाएं', 'दौरे की अवधि नोट करें'],
      es: ['Despeje objetos peligrosos', 'NO sujete al niño', 'Coloque de lado al terminar', 'Cronometre la duración'],
      fr: ['Dégagez les objets dangereux', 'Ne maintenez PAS l\'enfant', 'Mettez sur le côté après', 'Chronométrez la durée'],
      zh: ['清除危险物品', '不要按住孩子', '发作停止后侧卧', '记录发作持续时间'],
    }},
    adult: { steps: {
      en: ['Clear surroundings of hard objects', 'Do NOT put anything in the mouth', 'Place in recovery position after', 'Call emergency if seizure > 5 min'],
      hi: ['कठोर वस्तुएं हटाएं', 'मुंह में कुछ न डालें', 'बाद में रिकवरी स्थिति में रखें', '5 मिनट से अधिक हो तो कॉल करें'],
      es: ['Despeje objetos duros', 'NO ponga nada en la boca', 'Posición de recuperación después', 'Llame si dura > 5 min'],
      fr: ['Dégagez les objets durs', 'Ne mettez RIEN dans la bouche', 'Position de récupération après', 'Appelez si > 5 min'],
      zh: ['清除周围硬物', '不要往嘴里放任何东西', '发作后放置恢复位', '超过5分钟拨打急救'],
    }},
    senior: { steps: {
      en: ['Protect head with soft padding', 'Do not restrain movement', 'Check for injuries after seizure', 'Note time and any medications taken'],
      hi: ['सिर को नरम गद्दी से बचाएं', 'हलचल रोकें नहीं', 'दौरे के बाद चोटों की जांच करें', 'समय और दवाएं नोट करें'],
      es: ['Proteja la cabeza con algo suave', 'No restrinja el movimiento', 'Revise lesiones después', 'Anote tiempo y medicamentos'],
      fr: ['Protégez la tête', 'Ne restreignez pas', 'Vérifiez les blessures après', 'Notez le temps et médicaments'],
      zh: ['用软垫保护头部', '不要限制身体活动', '发作后检查是否受伤', '记录时间和用药情况'],
    }},
    pregnant: { steps: {
      en: ['Place on left side immediately', 'Protect from injury, clear area', 'This may be eclampsia - call 911', 'Monitor breathing after seizure'],
      hi: ['तुरंत बाईं ओर लिटाएं', 'चोट से बचाएं, जगह साफ करें', 'यह एक्लेम्पसिया हो सकता है', 'दौरे के बाद श्वास की निगरानी करें'],
      es: ['Coloque del lado izquierdo', 'Proteja de lesiones', 'Puede ser eclampsia - llame 911', 'Controle respiración después'],
      fr: ['Placez sur le côté gauche', 'Protégez des blessures', 'Possible éclampsie - appelez 15', 'Surveillez la respiration après'],
      zh: ['立即让患者左侧卧', '保护免受伤害，清理周围', '可能是子痫-拨打120', '发作后监测呼吸'],
    }},
  },
  poisoning: {
    child: { steps: {
      en: ['Do NOT induce vomiting', 'Try to identify the substance', 'Call poison control center', 'Save a sample of the substance'],
      hi: ['उल्टी कराने की कोशिश न करें', 'पदार्थ की पहचान करें', 'विष नियंत्रण केंद्र को कॉल करें', 'पदार्थ का नमूना बचाएं'],
      es: ['NO induzca el vómito', 'Identifique la sustancia', 'Llame al centro de toxicología', 'Guarde una muestra'],
      fr: ['Ne provoquez PAS de vomissement', 'Identifiez la substance', 'Appelez le centre antipoison', 'Gardez un échantillon'],
      zh: ['不要催吐', '尝试确认摄入的物质', '拨打中毒控制中心', '保存物质样本'],
    }},
    adult: { steps: {
      en: ['Do NOT induce vomiting', 'Identify the poison and amount', 'Call poison control immediately', 'If unconscious, place in recovery position'],
      hi: ['उल्टी न कराएं', 'जहर और मात्रा पहचानें', 'तुरंत विष नियंत्रण कॉल करें', 'बेहोश हो तो रिकवरी स्थिति में रखें'],
      es: ['NO induzca el vómito', 'Identifique el veneno y cantidad', 'Llame a toxicología', 'Si inconsciente, posición de recuperación'],
      fr: ['Ne provoquez PAS de vomissement', 'Identifiez le poison', 'Appelez le centre antipoison', 'Si inconscient, position de récupération'],
      zh: ['不要催吐', '确认毒物种类和剂量', '立即拨打中毒控制热线', '如失去意识放置恢复体位'],
    }},
    senior: { steps: {
      en: ['Check for medication overdose', 'Do not induce vomiting', 'Gather all medication bottles', 'Call emergency services with details'],
      hi: ['दवा की अधिक मात्रा जांचें', 'उल्टी न कराएं', 'सभी दवा की बोतलें इकट्ठा करें', 'विवरण के साथ आपातकालीन कॉल करें'],
      es: ['Verifique sobredosis de medicamentos', 'No induzca el vómito', 'Reúna todos los frascos', 'Llame con detalles'],
      fr: ['Vérifiez le surdosage', 'Ne provoquez pas de vomissement', 'Rassemblez les médicaments', 'Appelez avec les détails'],
      zh: ['检查是否药物过量', '不要催吐', '收集所有药瓶', '携带详细信息拨打急救'],
    }},
    pregnant: { steps: {
      en: ['Do NOT induce vomiting', 'Identify substance immediately', 'Call poison control - mention pregnancy', 'Position on left side'],
      hi: ['उल्टी न कराएं', 'तुरंत पदार्थ पहचानें', 'गर्भावस्था बताते हुए कॉल करें', 'बाईं ओर लिटाएं'],
      es: ['NO induzca el vómito', 'Identifique la sustancia', 'Llame mencionando el embarazo', 'Posicione del lado izquierdo'],
      fr: ['Ne provoquez PAS de vomissement', 'Identifiez la substance', 'Appelez en mentionnant la grossesse', 'Position sur le côté gauche'],
      zh: ['不要催吐', '立即确认物质', '拨打中毒热线-提及怀孕', '左侧卧位'],
    }},
  },
  choking: {
    child: { steps: {
      en: ['Give 5 back blows between shoulder blades', 'Then 5 chest thrusts (under 1 year)', 'For older children: abdominal thrusts', 'Call emergency if object not dislodged'],
      hi: ['कंधे के बीच 5 पीठ थपकी दें', '1 साल से कम: 5 छाती दबाव', 'बड़े बच्चों के लिए: पेट दबाव', 'वस्तु न निकले तो कॉल करें'],
      es: ['Dé 5 golpes en la espalda', 'Luego 5 compresiones torácicas', 'Niños mayores: compresiones abdominales', 'Llame si no se desaloja'],
      fr: ['Donnez 5 tapes dans le dos', 'Puis 5 compressions thoraciques', 'Enfants plus âgés: compressions abdominales', 'Appelez si non délogé'],
      zh: ['在肩胛骨之间拍打5次', '1岁以下：5次胸部按压', '较大儿童：腹部冲击法', '异物未排出请拨打急救'],
    }},
    adult: { steps: {
      en: ['Perform Heimlich maneuver (abdominal thrusts)', 'Stand behind, fist above navel', 'Give quick upward thrusts', 'If unconscious, begin CPR'],
      hi: ['हेम्लिक मैन्यूवर करें', 'पीछे खड़े हों, मुट्ठी नाभि के ऊपर', 'तेज ऊपर की ओर दबाव दें', 'बेहोश हो तो CPR शुरू करें'],
      es: ['Realice la maniobra de Heimlich', 'Párese detrás, puño sobre el ombligo', 'Dé empujes rápidos hacia arriba', 'Si inconsciente, inicie RCP'],
      fr: ['Effectuez la manoeuvre de Heimlich', 'Derrière le patient, poing au-dessus du nombril', 'Poussées rapides vers le haut', 'Si inconscient, commencez la RCP'],
      zh: ['执行海姆立克急救法（腹部冲击）', '站在身后，拳头放在肚脐上方', '快速向上冲击', '如失去意识开始心肺复苏'],
    }},
    senior: { steps: {
      en: ['Use gentle Heimlich maneuver', 'Be careful of fragile ribs', 'If seated, perform from behind chair', 'Monitor carefully after object removed'],
      hi: ['धीरे से हेम्लिक करें', 'कमजोर पसलियों का ध्यान रखें', 'बैठे हों तो कुर्सी के पीछे से करें', 'वस्तु निकलने के बाद निगरानी करें'],
      es: ['Use Heimlich suave', 'Cuidado con costillas frágiles', 'Si está sentado, desde atrás de la silla', 'Controle después de extraer'],
      fr: ['Heimlich doux', 'Attention aux côtes fragiles', 'Si assis, par derrière la chaise', 'Surveillez après extraction'],
      zh: ['轻柔执行海姆立克法', '注意脆弱的肋骨', '如坐着从椅子后方进行', '异物取出后仔细监测'],
    }},
    pregnant: { steps: {
      en: ['Use chest thrusts instead of abdominal', 'Place fist on center of breastbone', 'Give firm backward thrusts', 'Call emergency immediately'],
      hi: ['पेट के बजाय छाती दबाव दें', 'मुट्ठी छाती की हड्डी पर रखें', 'मजबूत पीछे की ओर दबाव दें', 'तुरंत आपातकालीन कॉल करें'],
      es: ['Use compresiones torácicas, no abdominales', 'Coloque puño en el esternón', 'Dé empujes firmes hacia atrás', 'Llame a emergencias'],
      fr: ['Compressions thoraciques, pas abdominales', 'Placez le poing sur le sternum', 'Poussées fermes vers l\'arrière', 'Appelez les urgences'],
      zh: ['使用胸部冲击代替腹部', '将拳头放在胸骨中央', '用力向后冲击', '立即拨打急救电话'],
    }},
  },
  childbirth: {
    child: { steps: {
      en: ['This is not applicable for children', 'Call emergency services immediately', 'Keep the child calm', 'Wait for medical professionals'],
      hi: ['यह बच्चों पर लागू नहीं', 'तुरंत आपातकालीन सेवा कॉल करें', 'बच्चे को शांत रखें', 'चिकित्सा पेशेवरों की प्रतीक्षा करें'],
      es: ['No aplica para niños', 'Llame a emergencias', 'Mantenga al niño calmado', 'Espere a los profesionales'],
      fr: ['Non applicable aux enfants', 'Appelez les urgences', 'Gardez l\'enfant calme', 'Attendez les professionnels'],
      zh: ['不适用于儿童', '立即拨打急救电话', '让孩子保持冷静', '等待医护人员'],
    }},
    adult: { steps: {
      en: ['Call emergency services immediately', 'Help mother into comfortable position', 'Have clean towels ready', 'Do not pull on the baby'],
      hi: ['तुरंत आपातकालीन सेवा कॉल करें', 'माँ को आरामदायक स्थिति में रखें', 'साफ तौलिए तैयार रखें', 'बच्चे को न खींचें'],
      es: ['Llame a emergencias', 'Ayude en posición cómoda', 'Tenga toallas limpias listas', 'No tire del bebé'],
      fr: ['Appelez les urgences', 'Position confortable pour la mère', 'Serviettes propres prêtes', 'Ne tirez pas sur le bébé'],
      zh: ['立即拨打急救电话', '帮助产妇采取舒适姿势', '准备好干净毛巾', '不要拉扯婴儿'],
    }},
    senior: { steps: {
      en: ['This is rare - call emergency immediately', 'Keep the patient comfortable', 'Have clean materials ready', 'Wait for professional help'],
      hi: ['यह दुर्लभ है - तुरंत कॉल करें', 'मरीज को आरामदायक रखें', 'साफ सामग्री तैयार रखें', 'पेशेवर मदद की प्रतीक्षा करें'],
      es: ['Es raro - llame a emergencias', 'Mantenga cómodo al paciente', 'Tenga materiales limpios', 'Espere ayuda profesional'],
      fr: ['Rare - appelez les urgences', 'Gardez le patient confortable', 'Matériaux propres prêts', 'Attendez l\'aide professionnelle'],
      zh: ['罕见情况-立即拨打急救', '让患者保持舒适', '准备好干净材料', '等待专业帮助'],
    }},
    pregnant: { steps: {
      en: ['Support mother in semi-upright position', 'Keep area clean with towels and sheets', 'Guide baby gently, do not pull', 'Keep baby warm, clear airway gently'],
      hi: ['माँ को अर्ध-सीधी स्थिति में सहारा दें', 'तौलिए से क्षेत्र साफ रखें', 'बच्चे को धीरे से गाइड करें', 'बच्चे को गर्म रखें, वायुमार्ग साफ करें'],
      es: ['Soporte semi-erguida a la madre', 'Mantenga limpio con toallas', 'Guíe al bebé suavemente', 'Mantenga al bebé abrigado'],
      fr: ['Soutenez en position semi-assise', 'Gardez propre avec des serviettes', 'Guidez le bébé doucement', 'Gardez le bébé au chaud'],
      zh: ['支撑产妇半直立位', '用毛巾保持区域清洁', '轻柔引导婴儿，不要拉', '保持婴儿温暖，轻柔清理气道'],
    }},
  },
};
